apiVersion: v1
kind: Service
metadata:
  name: chat-app-account-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: chat-app-account
  ports:
    - protocol: TCP
      port: {{ .Values.service.account.port }}
      targetPort: {{ .Values.service.account.port }}
  type: {{ .Values.service.type }}
