apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
  namespace: {{ .Values.namespace }}
data:
  REDIS_PASSWORD: {{ include "redis.password" . | 64enc}}
  authjwt_secret_key: {{ .Values.config.account.accessTokenKey | 64enc}}
  authjwt_access_cookie_key: {{ .Values.config.account.accessCookieKey | 64enc}}
  authjwt_refresh_cookie_key: {{ .Values.config.account.refreshCookieKey | 64enc}}
  authjwt_access_csrf_cookie_key: {{ .Values.config.account.csrfKey | 64enc}}
  authjwt_refresh_csrf_cookie_key: {{ .Values.config.account.csrfRefreshKey | 64enc}}
  ADMIN_USERNAME: {{ .Values.config.account.adminUsername | 64enc}}
  ADMIN_PASSWORD: {{ .Values.config.account.adminPassword | 64enc}}
