apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: {{ .Values.namespace}}
data:
  TESTING: {{ .Values.config.account.testing }}
  TEST_DATABASE_URL: {{ .Values.config.account.databaseUrl}}
  DATABASE_URL: {{ .Values.config.account.databaseUrl}}
  LOG_FILENAME: "chat_application.log"
  authjwt_access_token_expires: {{ .Values.config.account.accessTokenExpiration}}
  authjwt_refresh_token_expires: {{ .Values.config.account.refreshTokenExpiration}}
  REDIS_HOST: {{ .Values.dependencies.redisHost}}
  REDIS_PORT: {{ .Values.dependencies.redisPort}}
  REDIS_PASSWORD: {{ .Values.dependencies.redisPassword}}
  BROKER_URL: {{ .Values.dependencies.kafkaBrokerUrl}}
  ADMIN_EMAIL: {{ .Values.config.account.adminEmail}}
