apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-account
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-app-account
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chat-app-account
    spec:
      containers:
        - name: chat-app-account
          image: cyrildavif/chat_app_account:65c808a
          envFrom:
            - configMapRef:
                name: account-config
            - secretRef:
              name: account-secrets
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi

          ports:
            - containerPort: {{ .Values.service.account.port }}

          livenessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.service.account.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
