apiVersion: v1
kind: Service
metadata:
  name: chat-app-chat-svc
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: chat-app-chat
  ports:
    - protocol: TCP
      port: {{ .Values.service.chat.port}}
      targetPort: {{ .Values.service.chat.port}}
  type: {{ .Values.service.type}}
