apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-secrets
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
spec:
  template:
    metadata:
      name: chat-secrets
      namespace: {{ .Values.namespace }}
      creationTimestamp: null
  encryptedData:
    secrets.yaml: AgCADm+Kolzw+CWLCZ8YCL476EfFjRqcrv7OisAKqPd4J/oGRhXQE3Z+23QO2ACOLitabJt3KboGIIT4M3hF6VlcR6nNAIJe+mm6vSR7U1WjRPyEq+lHZ7WXGhHX30WYe3LJBelgknES/lDaIazVEaya/GEtosACXIgThnqlCAEqIHIP0H1gqY0qBux3V+WQ2JYhzw/yA4CnQO0D6DbtnfTqj9lGU4JTDxXP8iVb3q7ZwQbfFcs0cAbkYa7awEB0j6cOMItSyH5d/SNjYxF2uMzHAzDNwtw3X4hxMpbYahbIcm+/6VpUTOs7MMmuugAhgxc5LMFkxsiXG+QtDnpSfxrqtXHXxLB9R6jOBRzNB68DxiVFtxNRR66dZBAqAC6bB5arhC8GdTZBZH/fr3AO0pTU39jlKeW+QaPoaoH1ewWUZ+7+86xWlvte15uoenDqtSMN3xbnlQff9XuoM9vtsY8SCOOvryHsdrKwOopg/wxfgy3zLpe8tw3euRp4bhtOXqDvXQ8Mn0/3JGC/1WFbmUZ07yaMKgdUMiJ/6lG674caas2mEuAnOWYu8SAQ+CYzfaB8HwblGT8kr/CTEupJsHX2CVDcgSi/gZ4MI48zpQlELS3XRiOXu4GilKyL9yrjUE22jbM4MFHSEEGg7UJ5+GBTwsW+qNWyFF5r53V801HFbWz+lsK7e90NrN0JpdLCfthU4DK2lJ/jSGjuiUece0xFsagAxMsSuQ+a15xTg8Td8arSCEGfXTAlnC2HJBCn3Lm/jiitPRPXx3PVlQHE47TA1mFUo/JQzZFOEDGw4kQ+9Nihb+6ZLa6oAm0vmk6Ttkvurncpy0PLr5Dy78NMY+jmO9bjqJdLN1r5
