apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
  namespace: {{ .Values.namespace }}
data:
  REDIS_PASSWORD: {{ include "redis.password" . | 64enc}}
  SECRET_KEY: {{ .Values.config.chat.secret_key | 64enc}}
