apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: {{ .Values.namespace}}
data:
  TESTING: {{ .Values.config.chat.testing | quote}}
  LOG_FILENAME: "chat_application.log"
  AUTH_MANAGEMENT_URL: "http://chat-app-account-svc:8081"
  SUPPORT_URL: "http://chat-app-support-svc:8084"
  REDIS_HOST: {{ .Values.dependencies.redisHost | quote}}
  REDIS_PORT: {{ .Values.dependencies.redisPort | quote}}
  REDIS_PASSWORD: {{ include "redis.password" .}}
  ELASTICSEARCH_HOST: {{ .Values.dependencies.elasticsearchHost | quote}}
  ELASTICSEARCH_PORT: {{ .Values.dependencies.elasticsearchPort | quote}}
  JAEGER_HOST: {{ .Values.dependencies.jaegerHost | quote}}
  JAEGER_PORT: {{ .Values.dependencies.jaegerPort | quote}}
