apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: {{ .Values.namespace}}
data:
  TESTING: {{ .Values.config.chat.testing}}
  LOG_FILENAME: "chat_application.log"
  AUTH_MANAGEMENT_URL: "http://chat-app-account-svc:8081"
  SUPPORT_URL: "http://chat-app-support-svc:8084"
  REDIS_HOST: {{ .Values.dependencies.redisHost}}
  REDIS_PORT: {{ .Values.dependencies.redisPort}}
  REDIS_PASSWORD: {{ .Values.dependencies.redisPassword}}
  ELASTICSEARCH_HOST: {{ .Values.dependencies.elasticsearchHost}}
  ELASTICSEARCH_PORT: {{ .Values.dependencies.elasticsearchPort}}
  JAEGER_HOST: {{ .Values.dependencies.jaegerHost}}
  JAEGER_PORT: {{ .Values.dependencies.jaegerPort}}
