apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: {{ .Values.namespace }}
data:
  BROKER_URL: {{ .Values.dependencies.kafkaBrokerUrl}}
  CELERY_BROKER_URL: {{ .Values.config.notification.celery_url}}
  CELERY_RESULT_URL: {{ .Values.config.notification.celery_url}}
  STMP_SERVER: {{ .Values.config.notification.stmp_server_ip}}
  EMAIL_PORT: {{ .Values.config.notification.stmp_server_port}}
  EMAIL_SENDER: {{ .Values.config.notification.smtp_email }}
  ACCOUNT_SERVICE_URL: "http://chat-app-account-svc:8081"
  GRAFANA_SERVER_URL: {{ .Values.config.notification.grafana_url}}
