apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-secrets
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
spec:
  template:
    metadata:
      name: notification-secrets
      namespace: {{ .Values.namespace }}
      creationTimestamp: null
  encryptedData:
    secrets.yaml: AgBVuzbJxFQNEpSvOClpmDDWFC6a92On8wRiYhgzsMhPVBeLVtlUcsRHeAbSf8kt47e4VuBcMUA3fSM/M+bL9a7buy1Fe4ID/Cwl/WciI0lsn214UNH3vQj2F+UAC6PxSfKaOlCrLIIGoeZiSAhdzw6AIhlzE0S41Y/znOMp8Ttq1wVIQv69n4fyi8K4A0RSCWaAEIe5WVJOw2bEQgoZDRi8a5Sjeb387WTDC2RdUg1p9vRTVTmqK6JhTTPRqjrhBpKVq9+YKaETRpNX/IbNMV+NJcJmCce9N57msOOiwhO5C6Rm//soVFkMc2J6yudyO3Iw6k2f3GOUTZahfuP+MiJCrMiTXcGoQhFzV8C2FJvrpCYn68myvFhmd7920mFxiVCzrZUonh2YskWXGBSSIphjD7y+wnuupERFs6NPXENHGmQ2XC904pNtwiEOERsAPt5+uDKjJ2ZnjSKjvy6l3BguD8cd3pEbjK/aQywYJMxjhBDdJQ9zHmwB9JQa1Jhc3IvtAu9q6B8Eb2lYrOZl/m1MBCFK7fNtF7RDqRpyNUfG0N8ucL1l4s+/gO+Celscvp+PkmVs4SgLlQvHyQXmdnLrQAaF4NKG8NXEFSvLFM9m4Wzx6bMjIFTFWMK5uYhGFIZ4D/sELnHCaIGkOd5BlGs2MWFBn+ZvTd4PjkEfGB28v+wcuU/Yn/eh+JmRih0nNYP7NeQsDOt+MzRONdO2bBNwT9ovySXO7rebCMJW+ut1qfOELvxEExswp/zdGUqceAoxUAaIwvOrci/oGhxa1V5huluXcxBUeMEBFP1lQOzt2EMms/dvTv5xIshRs8B0pTcmaJSxhpqTdwVr81Wnbnp+61SN/emfObw4sxO1Hcw3IaiPM8wAv4+YP2zyPob+2JXPEBMJg6K8LjbH8QVJPhhyVSLwIAnr4JjlkKkoKA3UyZTRRlg+YuRyQKt6XsE6dSC5Rmg=

