apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: {{ .Values.namespace }}
data:
  EMAIL_PASSWORD: {{ .Values.config.notification.stmp_server_password | 64enc}}
  GRAFANA_ADMIN_USER: {{ .Values.config.account.adminUsername | 64enc}}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.config.account.adminPassword | 64enc}}
  MYSQL_USERNAME: {{ .Values.dependencies.mysqlUser | 64enc}}
  MYSQL_PASSWORD: {{ .Values.dependencies.mysqlPassword | 64enc}}
  MYSQL_HOST: {{ .Values.dependencies.mysqlHost | 64enc}}