apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-app-support
  namespace: {{ .Values.namespace}}
spec:
  secretName: chat-app-support-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - {{ .Values.dnsNames.name.support}}
