apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: chat-app-support
spec:
  tls:
    - hosts:
        - {{ .Values.dnsNames.name.support}}
      secretName: chat-app-support-certificate
  rules:
    - host: {{ .Values.dnsNames.name.support}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-app-support-svc
                port:
                  number: {{ .Values.service.support.port}}
