apiVersion: v1
kind: Service
metadata:
  name: chat-app-support-svc
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: chat-app-support
  ports:
    - protocol: TCP
      port: {{ .Values.service.support.port}}
      targetPort:  {{ .Values.service.support.port}}
  type: {{ .Values.service.type}}
