apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-support
spec:
  selector:
    matchLabels:
      app: chat-app-support
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chat-app-support
    spec:
      containers:
        - name: chat-app-support
          image: cyrildavif/chat_app_support:bc6cf01
          ports:
            - containerPort: 8084
