apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-app-account
  namespace: apps
spec:
  secretName: chat-app-account-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - account.hivechat.com
