apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: apps
data:
  TESTING: "True"
  TEST_DATABASE_URL: "sqlite:///./testing.db"
  LOG_FILENAME: "chat_application.log"
  authjwt_access_token_expires: "20"
  authjwt_refresh_token_expires: "1440"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  BROKER_URL: "kafka:9092"
  ADMIN_EMAIL: "admin@admin.com"
