apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  TESTING: "True"
  TEST_DATABASE_URL: "sqlite:///./testing.db"
  DATABASE_URL: "postgresql://admin:admin@postgres:6381/chat_app_database"
  LOG_FILENAME: "chat_application.log"
  authjwt_secret_key: "yoursecretkey"
  authjwt_access_token_expires: "20"
  authjwt_refresh_token_expires: "1440"
  authjwt_access_cookie_key: "youraccesscookiekey"
  authjwt_refresh_cookie_key: "yourrefreshcookiekey"
  authjwt_access_csrf_cookie_key: "youraccesscsrfcookiekey"
  authjwt_refresh_csrf_cookie_key: "yourrefreshcsrfcookiekey"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  BROKER_URL: "kafka:9092"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin"
  ADMIN_EMAIL: "admin@admin.com"
