apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-app-chat
  namespace: apps
spec:
  secretName: chat-app-chat-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - chat.hivechat.com
