apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-app-support
  namespace: apps
spec:
  secretName: chat-app-support-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - support.hivechat.com
