# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: apps

replicaCount: 1

# services for application
service:
  type: NodePort
  account:
    port: 8081
  notification:
    port: 8082
  chat:
    port: 8083
  support:
    port: 8084

# Domain names for application
dnsNames:
  name:
    account: account.hivechat.com
    chat: chat.hivechat.com
    notification: notification.hivechat.com
    support: support.hivechat.com

# application dependencies
dependencies:
  kafkaBrokerUrl: kafka:9092
  redisHost: redis
  redisPort: 6379
  redisPassword: ""
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9200
  jaegerHost: jaeger
  jaegerPort: 6831

# configuration for application services
config:
  account:
    testing: false
    databaseUrl: sqlite:///./testing.db
    accessTokenExpiration: 20
    refreshTokenExpiration: 1440
    adminEmail: admin@admin.com
  chat:
    testing: false
  notification:
    celery_url: redis://redis:6379/0
    celery_result_url: redis://redis:6379/0
    stmp_server_ip: stmp.server.ip
    stmp_server_port: 456
    smtp_email: admin@gmail.com
    grafana_url: http://grafana:3000
    
# ingress configuration
ingress:
  enabled: false
  class: nginx

# LetsEncrypt email address
letsencrypt:
  email: mydomain@gmail.com



image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 

imagePullSecrets: []
nameOverride: 
fullnameOverride: 

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
