apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configuration
data:
  account.config: |
    TESTING=False
    TEST_DATABASE_URL=sqlite:///./testing.db
    DATABASE_URL=postgresql://admin:admin@postgres:6381/chat_app_database
    LOG_FILENAME=chat_application.log
    authjwt_secret_key=yoursecretkey
    authjwt_access_token_expires=20
    authjwt_refresh_token_expires=1440
    authjwt_access_cookie_key='youraccesscookiekey'
    authjwt_refresh_cookie_key='yourrefreshcookiekey'
    authjwt_access_csrf_cookie_key='youraccesscsrfcookiekey'
    authjwt_refresh_csrf_cookie_key='yourrefreshcsrfcookiekey'
    REDIS_HOST=redis
    REDIS_PORT=6379
    REDIS_PASSWORD=""
    BROKER_URL=kafka:9092
    ADMIN_USERNAME=admin
    ADMIN_PASSWORD=admin
    ADMIN_EMAIL=admin@admin.com

  chat.config: |
    TESTING=false
    LOG_FILENAME=chat_application.log
    AUTH_MANAGEMENT_URL=http://chat-app-account-svc:8081
    SUPPORT_URL=http://chat-app-support-svc:8084
    REDIS_HOST=redis
    REDIS_PORT=6379
    ELASTICSEARCH_HOST=elasticsearch
    ELASTICSEARCH_PORT=9200
    JAEGER_HOST=jaeger
    JAEGER_PORT=6831
    SECRET_KEY=yourdjangosecretkey

  notification.config: |
    BROKER_URL=kafka:9092
    CELERY_BROKER_URL=redis://redis:6379/0
    CELERY_RESULT_URL=redis://redis:6379/0
    STMP_SERVER=youremailserverip
    EMAIL_PORT=youremailserverport
    EMAIL_SENDER=youremailaddress
    EMAIL_PASSWORD=youremailpassword
    ACCOUNT_SERVICE_URL=http://chat-app-account-svc:8081
    GRAFANA_ADMIN_USER=admin
    GRAFANA_ADMIN_PASSWORD=admin
    GRAFANA_SERVER_URL=http://grafana:3000
