apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: apps
data:
  BROKER_URL: "kafka:9092"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_URL: "redis://redis:6379/0"
  STMP_SERVER: "youremailserverip"
  EMAIL_PORT: "youremailserverport"
  EMAIL_SENDER: "youremailaddress"
  ACCOUNT_SERVICE_URL: "http://chat-app-account-svc:8081"
  GRAFANA_SERVER_URL: "http://grafana:3000"
